/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package etapp;
import java.sql.*;
import java.awt.Color;
import java.awt.Font;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Sara Mariam Raju
 */
public class adminpage extends javax.swing.JFrame {

    /**
     * Creates new form adminpage
     */
    public adminpage() {
        initComponents();
        usertable.getTableHeader().setFont(new Font("Segoe UI",Font.BOLD,12));
        usertable.getTableHeader().setOpaque(false);
        
        usertable.getTableHeader().setBackground(new Color(32,136,203));
        usertable.getTableHeader().setForeground(new Color(255,255,255));
        usertable.setRowHeight(25);
        
        
        try
        {
        Connection con = home.getConnection();
        Statement st = con.createStatement();
        
        String sql = "Select * from applicationform";
        
        ResultSet rs = st.executeQuery(sql);
        while(rs.next())
        {
        String n = rs.getString("name");
        
         String date = String.valueOf(rs.getDate("dob"));
         String ad= rs.getString("address");
        
        String mob = String.valueOf(rs.getInt("mobno"));
          String an = String.valueOf(rs.getInt("adharno"));
          
          String tbData[]={n,date,ad,mob,an};
          DefaultTableModel tb1model = (DefaultTableModel)usertable.getModel();
          
          tb1model.addRow(tbData);
        
        }
        }
        catch(Exception e)
        {JOptionPane.showMessageDialog(null,e);}
        
        
        
        
        try
        {
            Connection conn = home.getConnection();
            Statement sta = conn.createStatement();
            
              String sq = "Select * from deletetable";
        
        ResultSet res = sta.executeQuery(sq);
        
        while(res.next())
        {
        
         String na = res.getString("name");
        
         String dat = String.valueOf(res.getDate("dob"));
         String adr= res.getString("address");
        
         String mobn = String.valueOf(res.getInt("mobno"));
          String ad = String.valueOf(res.getInt("aadhaarno"));
          
            String tbData[]={na,dat,ad,mobn,ad};
          DefaultTableModel tb1model = (DefaultTableModel)deltable.getModel();
          
          tb1model.addRow(tbData);
        
        }
        }
        
          catch(Exception ex)
        {JOptionPane.showMessageDialog(null,ex);}
        
        
        try
        {
        Connection con = home.getConnection();
        Statement stb = con.createStatement();
        String sqa = "select * from accepttable";
        
        ResultSet rsl = stb.executeQuery(sqa);
        
         while(rsl.next())
        {
        
         String nam = rsl.getString("name");
        
         String dte = String.valueOf(rsl.getDate("dob"));
         String addr= rsl.getString("address");
        
         String mobno = String.valueOf(rsl.getInt("mobno"));
          String adha = String.valueOf(rsl.getInt("aadhaarno"));
          
            String tbData[]={nam,dte,addr,mobno,adha};
          DefaultTableModel tb1model = (DefaultTableModel)acctable.getModel();
          
          tb1model.addRow(tbData);
        
        }
        
        
        }
        
        catch(Exception exc)
        {JOptionPane.showMessageDialog(null,exc);}
        
        
        
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        newlist = new javax.swing.JButton();
        acceptlist = new javax.swing.JButton();
        rejectlist = new javax.swing.JButton();
        name = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        usertable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        acctable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        dlttable = new javax.swing.JScrollPane();
        deltable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 0, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        newlist.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        newlist.setText("NEW LIST");
        newlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newlistActionPerformed(evt);
            }
        });
        jPanel1.add(newlist, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 190, 30));

        acceptlist.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        acceptlist.setText("ACCEPT LIST");
        acceptlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptlistActionPerformed(evt);
            }
        });
        jPanel1.add(acceptlist, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 190, 30));

        rejectlist.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rejectlist.setText("REJECT LIST");
        rejectlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rejectlistActionPerformed(evt);
            }
        });
        jPanel1.add(rejectlist, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 190, 30));
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 200, -1));

        jButton1.setText("ACCEPT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 100, -1));

        jButton2.setText("REJECT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 480, 90, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 0, 200, 510));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setFocusable(false);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(452, 390));

        usertable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "DOB", "Address", "Mobno", "Adhaarno"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        usertable.setRowHeight(25);
        usertable.setSelectionBackground(new java.awt.Color(232, 57, 35));
        usertable.setSelectionForeground(new java.awt.Color(255, 255, 255));
        usertable.setShowHorizontalLines(true);
        usertable.getTableHeader().setReorderingAllowed(false);
        usertable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usertableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(usertable);

        jTabbedPane1.addTab("tab1", jScrollPane1);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        acctable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "DOB", "Address", "Mobno", "Aadhaarno"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        acctable.setGridColor(new java.awt.Color(0, 0, 0));
        acctable.setOpaque(false);
        acctable.setRowHeight(25);
        acctable.setSelectionBackground(new java.awt.Color(102, 102, 255));
        acctable.setSelectionForeground(new java.awt.Color(255, 255, 255));
        acctable.setShowHorizontalLines(true);
        jScrollPane3.setViewportView(acctable);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTabbedPane1.addTab("tab2", jPanel3);

        deltable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "DOB", "Address", "Mobno", "Adhaarno"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        dlttable.setViewportView(deltable);

        jScrollPane2.setViewportView(dlttable);

        jTabbedPane1.addTab("tab3", jScrollPane2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, -10, 460, 510));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 460, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int i = usertable.getSelectedRow();

        TableModel model = usertable.getModel();

        try
        {
            Connection con = home.getConnection();
            String sql = "insert into deletetable values(?,?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(sql);

            String name,dob,add,mob,adh;
            name = model.getValueAt(i, 0).toString();
            dob = model.getValueAt(i, 1).toString();
            add = model.getValueAt(i, 2).toString();
            mob = model.getValueAt(i, 3).toString();
            adh = model.getValueAt(i, 4).toString();

            pst.setString(1,name);

            pst.setString(2, dob);
            pst.setString(3, add);
            pst.setInt(4, Integer.parseInt(mob));
            pst.setInt(5, Integer.parseInt(adh));

            pst.executeUpdate();
        }

        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }

        try
        {
            Connection conn = home.getConnection();
            String  sq = "delete from applicationform where name = ? or adharno = ?";

            PreparedStatement ps = conn.prepareStatement(sq);
            ps.setString(1,null);
            ps.setString(2, name.getText());
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null,"REJECTED");

        }

        catch(Exception ex)
        { JOptionPane.showMessageDialog(null,ex);}

    }//GEN-LAST:event_jButton2ActionPerformed

    private void usertableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usertableMouseClicked
        // TODO add your handling code here:

        int i = usertable.getSelectedRow();

        TableModel model = usertable.getModel();

        name.setText(model.getValueAt(i,4).toString());
    }//GEN-LAST:event_usertableMouseClicked

    private void newlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newlistActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
        name.setVisible(true);
        jButton1.setVisible(true);
        jButton2.setVisible(true);
        
    }//GEN-LAST:event_newlistActionPerformed

    private void acceptlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptlistActionPerformed
        // TODO add your handling code here:
         jTabbedPane1.setSelectedIndex(1);
           name.setVisible(false);
        jButton1.setVisible(false);
        jButton2.setVisible(false);
    }//GEN-LAST:event_acceptlistActionPerformed

    private void rejectlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rejectlistActionPerformed
        // TODO add your handling code here:
         jTabbedPane1.setSelectedIndex(2);
           name.setVisible(false);
        jButton1.setVisible(false);
        jButton2.setVisible(false);
    }//GEN-LAST:event_rejectlistActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
         int i = usertable.getSelectedRow();

        TableModel model = usertable.getModel();

        try
        {
            Connection con = home.getConnection();
            String sql = "insert into accepttable values(?,?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(sql);

            String name,dob,add,mob,adh;
            name = model.getValueAt(i, 0).toString();
            dob = model.getValueAt(i, 1).toString();
            add = model.getValueAt(i, 2).toString();
            mob = model.getValueAt(i, 3).toString();
            adh = model.getValueAt(i, 4).toString();

            pst.setString(1,name);

            pst.setString(2, dob);
            pst.setString(3, add);
            pst.setInt(4, Integer.parseInt(mob));
            pst.setInt(5, Integer.parseInt(adh));

            pst.executeUpdate();
        }

        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
        
          try
        {
            Connection conn = home.getConnection();
            String  sq = "delete from applicationform where name = ? or adharno = ?";

            PreparedStatement ps = conn.prepareStatement(sq);
            ps.setString(1,null);
            ps.setString(2, name.getText());
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null,"ACCEPTED");

        }

        catch(Exception ex)
        { JOptionPane.showMessageDialog(null,ex);}

        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptlist;
    private javax.swing.JTable acctable;
    private javax.swing.JTable deltable;
    private javax.swing.JScrollPane dlttable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField name;
    private javax.swing.JButton newlist;
    private javax.swing.JButton rejectlist;
    private javax.swing.JTable usertable;
    // End of variables declaration//GEN-END:variables
}
