/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package etapp;


import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Sara Mariam Raju
 */
public class applicationform extends javax.swing.JFrame {

Connection con=null;
    /**
     * Creates new form applicationform
     */
    public applicationform() {
        initComponents();
        
        namee.setBackground(new java.awt.Color(0,0,0,1));
        
        addresss.setBackground(new java.awt.Color(0,0,0,1));
        
        dobb.setBackground(new java.awt.Color(0,0,0,1));
        mobb.setBackground(new java.awt.Color(0,0,0,1));
        adharr.setBackground(new java.awt.Color(0,0,0,1));
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        name = new javax.swing.JLabel();
        namee = new javax.swing.JTextField();
        dob = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        mob = new javax.swing.JLabel();
        mobb = new javax.swing.JTextField();
        adhar = new javax.swing.JLabel();
        adharr = new javax.swing.JTextField();
        register = new javax.swing.JButton();
        application = new javax.swing.JLabel();
        dobb = new com.toedter.calendar.JDateChooser();
        addresss = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(570, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        name.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        name.setText("NAME");
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 110, 30));

        namee.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jPanel1.add(namee, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 250, 30));

        dob.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        dob.setText("DATE OF BIRTH");
        jPanel1.add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 150, 30));

        address.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        address.setText("ADDRESS");
        jPanel1.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 140, 30));

        mob.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mob.setText("MOBILE NO");
        jPanel1.add(mob, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 120, -1));

        mobb.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        mobb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobbActionPerformed(evt);
            }
        });
        jPanel1.add(mobb, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 250, 30));

        adhar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        adhar.setText("ADHAR NO");
        jPanel1.add(adhar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 100, 20));

        adharr.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jPanel1.add(adharr, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 312, 250, 30));

        register.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        register.setText("REGISTER");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        jPanel1.add(register, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, 120, 30));

        application.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        application.setText("APPLICATION FORM PAGE");
        jPanel1.add(application, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 310, -1));

        dobb.setOpaque(false);
        jPanel1.add(dobb, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 250, -1));

        addresss.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jPanel1.add(addresss, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 290, 30));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 120, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagepack/881514 (1).jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 410));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mobbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobbActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        // TODO add your handling code here:
        
        try
        {
          Connection con = home.getConnection();
         
         String sql = "insert into applicationform values(?,?,?,?,?)";
         
         
         PreparedStatement pst =con.prepareStatement(sql);
          
          pst.setString(1,namee.getText());
          String date;
          SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
          date = sdf.format(dobb.getDate());
          pst.setString(2,date);
          
          
           pst.setString(3,addresss.getText());
            pst.setDouble(4,Integer.parseInt(mobb.getText()));
            pst.setDouble(5,Integer.parseInt(adharr.getText()));
          
          pst.executeUpdate();
          JOptionPane.showMessageDialog(null,"REGISTERED SUCESSFULLY");
           
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
        
        try
        {
        Connection conn = home.getConnection();
        String Sq = "Insert into user values(?,?)";
        PreparedStatement ps = conn.prepareStatement(Sq);
        
        ps.setString(1, namee.getText());
        ps.setDouble(2, Float.parseFloat(adharr.getText()));
        
        ps.executeUpdate();
        
        }
        
        catch(Exception ex)
        {JOptionPane.showMessageDialog(null,ex);}
        
        
    }//GEN-LAST:event_registerActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        userlogin u = new userlogin();
        u.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(applicationform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(applicationform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(applicationform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(applicationform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new applicationform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel address;
    private javax.swing.JTextField addresss;
    private javax.swing.JLabel adhar;
    private javax.swing.JTextField adharr;
    private javax.swing.JLabel application;
    private javax.swing.JLabel dob;
    private com.toedter.calendar.JDateChooser dobb;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mob;
    private javax.swing.JTextField mobb;
    private javax.swing.JLabel name;
    private javax.swing.JTextField namee;
    private javax.swing.JButton register;
    // End of variables declaration//GEN-END:variables
}
