/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package etapp;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Sara Mariam Raju
 */
public class userlogin extends javax.swing.JFrame {

    /**
     * Creates new form userlogin
     */
    public userlogin() {
        initComponents();
        namee.setBackground(new java.awt.Color(0,0,0,1));
        adharnoo.setBackground(new java.awt.Color(0,0,0,1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        name = new javax.swing.JLabel();
        namee = new javax.swing.JTextField();
        adharno = new javax.swing.JLabel();
        login = new javax.swing.JButton();
        adharnoo = new javax.swing.JTextField();
        userlogin = new javax.swing.JLabel();
        reg = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        name.setBackground(new java.awt.Color(255, 255, 255));
        name.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 255));
        name.setText("NAME :");
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 110, -1));

        namee.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        namee.setForeground(new java.awt.Color(255, 255, 255));
        namee.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        namee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameeActionPerformed(evt);
            }
        });
        jPanel1.add(namee, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 260, 30));

        adharno.setBackground(new java.awt.Color(255, 255, 255));
        adharno.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        adharno.setForeground(new java.awt.Color(255, 255, 255));
        adharno.setText("AADHAR NO :");
        jPanel1.add(adharno, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 130, 30));

        login.setBackground(new java.awt.Color(153, 0, 255));
        login.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        login.setForeground(new java.awt.Color(255, 255, 255));
        login.setText("LOGIN");
        login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        jPanel1.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 130, 30));

        adharnoo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        adharnoo.setForeground(new java.awt.Color(255, 255, 255));
        adharnoo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jPanel1.add(adharnoo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 260, 30));

        userlogin.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        userlogin.setForeground(new java.awt.Color(153, 255, 255));
        userlogin.setText("USER LOGIN");
        jPanel1.add(userlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 240, 40));

        reg.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        reg.setForeground(new java.awt.Color(153, 255, 255));
        reg.setText("NEW MEMBER : CLICK HERE TO REGISTER");
        reg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                regMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                regMouseExited(evt);
            }
        });
        jPanel1.add(reg, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, -1, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagepack/1867045 (1).jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 420));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameeActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
                // TODO add your handling code here:
                
             try
             {
             Connection con = home.getConnection();
             
             String sql = "select * from user where name = ? and aadhaarno =?";
             
             PreparedStatement ps = con.prepareStatement(sql);
           
             
             ps.setString(1, namee.getText());
              ps.setInt(2,Integer.parseInt(adharnoo.getText()));
             
             ResultSet rs = ps.executeQuery();
             if(rs.next())
             {
             JOptionPane.showMessageDialog(null,"WELCOME"+ namee.getText());
             }
             
             
             }
             catch(Exception e)
             {JOptionPane.showMessageDialog(null,e);}
                
                
                
    }//GEN-LAST:event_loginActionPerformed

    private void regMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regMouseEntered
        // TODO add your handling code here:
        reg.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_regMouseEntered

    private void regMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regMouseExited
        // TODO add your handling code here:
        reg.setForeground(new java.awt.Color(153,255,255));
    }//GEN-LAST:event_regMouseExited

    private void regMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regMouseClicked
        // TODO add your handling code here:
        applicationform ap=new applicationform();
        ap.setVisible(true);
        dispose();
               
    }//GEN-LAST:event_regMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userlogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adharno;
    private javax.swing.JTextField adharnoo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton login;
    private javax.swing.JLabel name;
    private javax.swing.JTextField namee;
    private javax.swing.JLabel reg;
    private javax.swing.JLabel userlogin;
    // End of variables declaration//GEN-END:variables

    void setvisible(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
